import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  API_PATH_PREFIXES,
  CACHE_NAME,
  PRECACHE_URLS,
} from '../src/lib/pwa-cache.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outputPath = join(__dirname, '../public/sw.js')

const swSource = `// Generated by scripts/generate-sw.ts — do not edit manually.
const CACHE_NAME = '${CACHE_NAME}'

const PRECACHE_URLS = ${JSON.stringify(PRECACHE_URLS, null, 2)}

const API_PATH_PREFIXES = ${JSON.stringify(API_PATH_PREFIXES, null, 2)}

function isApiRequest(url) {
  return API_PATH_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))
}

function isStaticAsset(url) {
  return /\\.(css|js|png|ico|svg|woff2?|json|html)$/.test(url.pathname)
}

function isCacheableResponse(response) {
  return (
    response.ok &&
    !response.redirected &&
    response.status >= 200 &&
    response.status < 300
  )
}

function isServeableCachedResponse(response) {
  return response.status >= 200 && response.status < 300
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  )
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      ),
  )
  self.clients.claim()
})

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') {
    return
  }

  const url = new URL(event.request.url)

  if (isApiRequest(url)) {
    return
  }

  // Navigation bypasses the service worker so Safari never receives redirect
  // responses from respondWith() ("Response served by service worker has
  // redirections").
  if (event.request.mode === 'navigate') {
    return
  }

  if (isStaticAsset(url)) {
    event.respondWith(
      caches.match(event.request).then((cached) => {
        if (cached && isServeableCachedResponse(cached)) {
          return cached
        }

        return fetch(event.request).then((response) => {
          if (!isCacheableResponse(response)) {
            return response
          }

          const copy = response.clone()
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, copy)
          })
          return response
        })
      }),
    )
  }
})
`

writeFileSync(outputPath, swSource)
console.log(`Generated ${outputPath}`)
